### ISSUE TITLE
it seems this plugin doesn't work with 1.7.5

### ISSUE THREAD

**Issue by fardina** [arjunsuresh/q2a-theme-switch#1]
Hi

Thank you for your plugin. Did you test this on 1.7.5?
It didn't work for me.

Thanks.

**Comment by arjunsuresh** [comment]
Yes, I use it on my site running 1.8 devel version and it should run on 1.7.5. Did you turn it on from Admins-Plugins?

**Comment by fardina** [comment]
Yes and switched the plugin to SnowLight([http://question2answer.org/qa/59992/new-theme-snowlight-minimalist-version-of-snowflat](url) )but after save everything disappear except the profile image:
![switch](https://user-images.githubusercontent.com/13521621/31502794-e9857314-af7a-11e7-8b0d-335ccf1fba37.png)
here is a larger image:
![switch2](https://user-images.githubusercontent.com/13521621/31502897-1b0a3ef6-af7b-11e7-919b-1d3d60dab70e.png)

**Comment by arjunsuresh** [comment]
Oh. You mean you chose the theme from your account page? What happens when you choose say "Snow" theme?

**Comment by fardina** [comment]
Yes I clicked on edit profile and there choosed the snowlight theme. I couldn't choose another theme because I just see my profile picture and nothing else!
So I have to delete the snowlight theme. And now I could switch between themes. So It seems this issue was because of snowlight theme?
Thank you 👍

**Comment by arjunsuresh** [comment]
yes, probably :)
